Hass-Alarm/Areas/Admin/Controllers/ActionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hass_Alarm.Data;
using Hass_Alarm.Data.Models;
using Microsoft.AspNetCore.Authorization;

namespace Hass_Alarm.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = "Admin,Manager")]
    public class ActionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ActionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Actions
        public async Task<IActionResult> Index()
        {
            return View(await _context.Actions.ToListAsync());
        }

        // GET: Admin/Actions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var action = await _context.Actions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (action == null)
            {
                return NotFound();
            }

            return View(action);
        }

        // GET: Admin/Actions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Actions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ActionGroupId,Name,Input_Boolean_EntityId,Input_Boolean_SetState,Service_Domain,Service_Name,Service_Fields")] Data.Models.Action action)
        {
            if (ModelState.IsValid)
            {
                _context.Add(action);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(action);
        }

        // GET: Admin/Actions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var action = await _context.Actions.FindAsync(id);
            if (action == null)
            {
                return NotFound();
            }
            return View(action);
        }

        // POST: Admin/Actions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ActionGroupId,Name,Input_Boolean_EntityId,Input_Boolean_SetState,Service_Domain,Service_Name,Service_Fields")] Data.Models.Action action)
        {
            if (id != action.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(action);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActionExists(action.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(action);
        }

        // GET: Admin/Actions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var action = await _context.Actions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (action == null)
            {
                return NotFound();
            }

            return View(action);
        }

        // POST: Admin/Actions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var action = await _context.Actions.FindAsync(id);
            _context.Actions.Remove(action);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActionExists(int id)
        {
            return _context.Actions.Any(e => e.Id == id);
        }
    }
}

Hass-Alarm/Areas/Admin/Controllers/PinCodesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hass_Alarm.Data;
using Hass_Alarm.Data.Models;
using Microsoft.AspNetCore.Authorization;

namespace Hass_Alarm.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = "Admin,Manager")]
    public class PinCodesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PinCodesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/PinCodes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.PinCodes.Include(p => p.ActionGroup);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Admin/PinCodes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pinCode = await _context.PinCodes
                .Include(p => p.ActionGroup)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pinCode == null)
            {
                return NotFound();
            }

            return View(pinCode);
        }

        // GET: Admin/PinCodes/Create
        public IActionResult Create()
        {
            ViewData["ActionGroupId"] = new SelectList(_context.ActionGroups, "Id", "Name");
            return View();
        }

        // POST: Admin/PinCodes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Pin,Name,Enabled,ActionGroupId")] PinCode pinCode)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pinCode);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ActionGroupId"] = new SelectList(_context.ActionGroups, "Id", "Name", pinCode.ActionGroupId);
            return View(pinCode);
        }

        // GET: Admin/PinCodes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pinCode = await _context.PinCodes.FindAsync(id);
            if (pinCode == null)
            {
                return NotFound();
            }
            ViewData["ActionGroupId"] = new SelectList(_context.ActionGroups, "Id", "Name", pinCode.ActionGroupId);
            return View(pinCode);
        }

        // POST: Admin/PinCodes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Pin,Name,Enabled,ActionGroupId")] PinCode pinCode)
        {
            if (id != pinCode.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pinCode);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PinCodeExists(pinCode.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ActionGroupId"] = new SelectList(_context.ActionGroups, "Id", "Id", pinCode.ActionGroupId);
            return View(pinCode);
        }

        // GET: Admin/PinCodes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pinCode = await _context.PinCodes
                .Include(p => p.ActionGroup)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pinCode == null)
            {
                return NotFound();
            }

            return View(pinCode);
        }

        // POST: Admin/PinCodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pinCode = await _context.PinCodes.FindAsync(id);
            _context.PinCodes.Remove(pinCode);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PinCodeExists(int id)
        {
            return _context.PinCodes.Any(e => e.Id == id);
        }
    }
}

Hass-Alarm/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hass_Alarm.Areas.Admin.Models.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Hass_Alarm.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = "Admin")]

    public class UsersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IConfiguration _configuration;

        public UsersController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager, IConfiguration configuration) {
            _userManager = userManager;
            _roleManager = roleManager;
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            var users = _userManager.Users.ToArray();
            return View(users);
        }

        public async Task<IActionResult> EditAsync(string id) {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();
            ViewData["User"] = user;
            var model = new EditUserModel();
            model.UserId = id;
            model.Admin = await _userManager.IsInRoleAsync(user, "Admin");
            model.Manager = await _userManager.IsInRoleAsync(user, "Manager");
            model.Member = await _userManager.IsInRoleAsync(user, "Member");
            return View(model);
        }

        [ValidateAntiForgeryToken, HttpPost]
        public async Task<IActionResult> EditAsync(EditUserModel model) {
            var user = await _userManager.FindByIdAsync(model.UserId);
            var admin = await _userManager.IsInRoleAsync(user, "Admin");
            var manager = await _userManager.IsInRoleAsync(user, "Manager");
            var member = await _userManager.IsInRoleAsync(user, "Member");
            if (model.Admin != admin) {
                if (model.Admin)
                    await _userManager.AddToRoleAsync(user, "Admin");
                else
                    await _userManager.RemoveFromRoleAsync(user, "Admin");
            }
            if (model.Manager != manager) {
                if (model.Manager)
                    await _userManager.AddToRoleAsync(user, "Manager");
                else
                    await _userManager.RemoveFromRoleAsync(user, "Manager");
            }
            if (model.Member != member) {
                if (model.Member)
                    await _userManager.AddToRoleAsync(user, "Member");
                else
                    await _userManager.RemoveFromRoleAsync(user, "Member");
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteAsync(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();
            var poweruser = new IdentityUser
            {

                UserName = _configuration["Admin:UserName"],
                Email = _configuration["Admin:Email"],
            };
            if (user.Email.ToLower() == poweruser.Email.ToLower() || user.UserName.ToLower() == poweruser.UserName.ToLower())
            {
                return RedirectToAction("Index");
            }
            
            return View(user);
        }

        [ValidateAntiForgeryToken, HttpPost]
        public async Task<IActionResult> ConfirmDeleteAsync(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();
            var poweruser = new IdentityUser
            {

                UserName = _configuration["Admin:UserName"],
                Email = _configuration["Admin:Email"],
            };
            if (user.Email.ToLower() == poweruser.Email.ToLower() || user.UserName.ToLower() == poweruser.UserName.ToLower())
            {
                return RedirectToAction("Index");
            }
            await _userManager.DeleteAsync(user);
            return RedirectToAction("Index");
        }
    }
}

Hass-Alarm/Views/Shared/_Layout.cshtml
@addTagHelper *, Hass-Alarm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hass_Alarm</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" />
    </environment>
    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />

    </environment>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hass_Alarm</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Panel">Panel</a>
                        </li>

                        <li class="nav-item" asp-authorize asp-roles="Manager,Admin">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Actions" asp-action="Index">Actions</a>
                        </li>
                        <li class="nav-item" asp-authorize asp-roles="Manager,Admin">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="ActionGroups" asp-action="Index">Action Groups</a>
                        </li>
                        <li class="nav-item" asp-authorize asp-roles="Manager,Admin">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="PinCodes" asp-action="Index">Pin Codes</a>
                        </li>

                        <li class="nav-item" asp-authorize asp-roles="Admin">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Hass_Alarm - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <environment exclude="Development">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <environment include="Development">
        <script src="~/js/site.js" asp-append-version="true"></script>

    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>